### ISSUE TITLE
[Refactor] 코드 스플리팅

### ISSUE THREAD

**Issue by lha0** [SSAFY-DamDa/DamDa_client#65]
## 📢Subject
JS

<br/>

## 📌Purpose

성능 최적화를 위한 코드 스플리팅 및 컴포넌트 지연로딩

<br/>

## ✅To-do
- [x] LightHouse 점수 측정 및 문제점 분석
- [x] webpack-bundle-analyzer 설치 및 분석
- [x] 코드 스플리팅 및 지연로딩 적용

<br/>

## 🏷etc
책 "프론트엔드 성능 최적화" - 유동균
