### ISSUE TITLE
[Feature] 절차형 페이지 스토리북 추가

### ISSUE THREAD

**Issue by PoeySK** [SSAFY-DamDa/DamDa_client#70]
## 📢Subject

Storybook, page
<br/>

## 📌Purpose

조건이 있는 페이지를 스토리로 작성하여 UI 테스트에 용이하도록 함
<br/>

## ✅To-do

- [x] AI 제작 결과 페이지
- [x] FAQ 어드민 전용 페이지
- [x] 리뷰 작성 모달

<br/>
