### ISSUE TITLE
[Refactor] 성능 개선

### ISSUE THREAD

**Issue by lha0** [SSAFY-DamDa/DamDa_client#71]
## 📢Subject

JS, CSS, Performance

<br/>

## 📌Purpose

Performance 성능 개선
- 이미지 최적화, 포맷 변경, 병목 코드 개선 등
<br/>

## ✅To-do

- [ ] 이미지 스크롤에 따른 최적화
- [ ] 이미지 포맷 webp으로 변경
- [ ] 병목 코드 찾기 및 개선

<br/>

## 🏷etc
📕Book "프론트엔드 성능 최적화 가이드" - 유동균
